// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Secret struct {
	ID             int64
	Name           string
	Value          []byte
	CurrentVersion int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type SecretVersion struct {
	ID        int64
	SecretID  int64
	Version   int64
	Value     []byte
	CreatedAt time.Time
}
