// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secret_versions.sql

package db

import (
	"context"
)

const insertSecretVersion = `-- name: InsertSecretVersion :one
INSERT INTO secret_versions (
    secret_id, version, value
) VALUES (
    ?1, ?2, ?3
)
RETURNING id, secret_id, version, value, created_at
`

type InsertSecretVersionParams struct {
	SecretID string
	Version  int64
	Value    []byte
}

func (q *Queries) InsertSecretVersion(ctx context.Context, arg InsertSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRowContext(ctx, insertSecretVersion, arg.SecretID, arg.Version, arg.Value)
	var i SecretVersion
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.Version,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}
