// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package db

import (
	"context"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (name, value) VALUES (?1, ?2)
RETURNING id, name, value, current_version, created_at, updated_at
`

type CreateSecretParams struct {
	Name  string
	Value []byte
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, createSecret, arg.Name, arg.Value)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretById = `-- name: GetSecretById :one
SELECT id, name, value, current_version, created_at, updated_at FROM secrets
WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetSecretById(ctx context.Context, id int64) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecretById, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretByName = `-- name: GetSecretByName :one
SELECT id, name, value, current_version, created_at, updated_at FROM secrets
WHERE name = ?1 LIMIT 1
`

func (q *Queries) GetSecretByName(ctx context.Context, name string) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecretByName, name)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, name, value, current_version, created_at, updated_at FROM secrets
ORDER BY name
`

func (q *Queries) ListSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.CurrentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
