// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package db

import (
	"context"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (
    id, name, value
) VALUES (
    ?1, ?2, ?3
)
RETURNING id, name, value, current_version, created_at, updated_at
`

type CreateSecretParams struct {
	ID    string
	Name  string
	Value []byte
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, createSecret, arg.ID, arg.Name, arg.Value)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets
WHERE id = ?1
`

func (q *Queries) DeleteSecret(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, id)
	return err
}

const getSecretById = `-- name: GetSecretById :one
SELECT id, name, value, current_version, created_at, updated_at FROM secrets
WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetSecretById(ctx context.Context, id string) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecretById, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, name, value, current_version, created_at, updated_at FROM secrets
ORDER BY name
`

func (q *Queries) ListSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.CurrentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets SET
    name = ?2,
    value = ?3,
    current_version = current_version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1 AND current_version = ?4
RETURNING id, name, value, current_version, created_at, updated_at
`

type UpdateSecretParams struct {
	ID             string
	Name           string
	Value          []byte
	CurrentVersion int64
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, updateSecret,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.CurrentVersion,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
