// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Secret struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	VersionID sql.NullInt64
}

type SecretVersion struct {
	ID        int64
	SecretID  string
	Version   int64
	Value     []byte
	CreatedAt time.Time
}
