// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (
    id, name, version_id
) VALUES (
    ?1, ?2, NULL
)
RETURNING id, name, created_at, updated_at, version_id
`

type CreateSecretParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, createSecret, arg.ID, arg.Name)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets
WHERE id = ?1
`

func (q *Queries) DeleteSecret(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, id)
	return err
}

const getSecretById = `-- name: GetSecretById :one
SELECT secrets.id, secrets.name, secrets.created_at, secrets.updated_at, secrets.version_id, secret_versions.value FROM secrets
JOIN secret_versions ON secrets.version_id = secret_versions.id
WHERE secrets.id = ?1 LIMIT 1
`

type GetSecretByIdRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	VersionID sql.NullInt64
	Value     []byte
}

func (q *Queries) GetSecretById(ctx context.Context, id string) (GetSecretByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getSecretById, id)
	var i GetSecretByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
		&i.Value,
	)
	return i, err
}

const insertVersionIntoSecret = `-- name: InsertVersionIntoSecret :one
UPDATE secrets SET
    version_id = ?2
WHERE id = ?1 AND version_id IS NULL
RETURNING id, name, created_at, updated_at, version_id
`

type InsertVersionIntoSecretParams struct {
	ID        string
	VersionID sql.NullInt64
}

func (q *Queries) InsertVersionIntoSecret(ctx context.Context, arg InsertVersionIntoSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, insertVersionIntoSecret, arg.ID, arg.VersionID)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, name, created_at, updated_at, version_id FROM secrets
ORDER BY name
`

func (q *Queries) ListSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets SET
    name = ?1,
    version_id = ?2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?3 AND version_id = ?4
RETURNING id, name, created_at, updated_at, version_id
`

type UpdateSecretParams struct {
	Name         string
	VersionID    sql.NullInt64
	ID           string
	OldVersionID sql.NullInt64
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, updateSecret,
		arg.Name,
		arg.VersionID,
		arg.ID,
		arg.OldVersionID,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
	)
	return i, err
}
